language: cpp

compiler:
  - gcc

branches:
  only:
    - master-merge-cmake
    - add-imgcodecs
    - test
    - concurrency

before_install: true
install: true
 
before_script:
  - mkdir bin
  - cd bin
  - cmake ..

script: make

after_success: true
after_failure: true
after_script: true
 
notifications:
  email: maxim.kostin@akvelon.net
